# Taskfile.yml
version: '3'

vars:
  INCOMING: src/content/reviews/ja/_incoming
  HERO_DIR: public/hero
  GRAPHS_DIR: public/graphs
  TARGETS_CMD: "node scripts/targets.mjs"

tasks:
  pipeline:
    desc: 変換→アセット→AI→最終整形
    deps: [convert, assets, ai, postocess]

  codex:validate-frontmatter:
    cmds:
      - FILES=$({{.TARGETS_CMD}}); node scripts/run_codex.mjs doc/playbooks/10_validate_frontmatter.md $FILES

  codex:fix-tables:
    cmds:
      - FILES=$({{.TARGETS_CMD}}); node scripts/run_codex.mjs doc/playbooks/11_fix_tables.md $FILES

  codex:fix-links:
    cmds:
      - FILES=$({{.TARGETS_CMD}}); node scripts/run_codex.mjs doc/playbooks/12_fix_links_footnotes.md $FILES

  codex:lint:
    cmds:
      - FILES=$({{.TARGETS_CMD}}); node scripts/run_codex.mjs doc/playbooks/13_lint.md $FILES

  debug:targets:
    cmds:
      - FILES=$({{.TARGETS_CMD}}); echo "$FILES"; echo "count=$(echo $FILES | wc -w)"

  codex:normalize-refs:
    desc: Step 2a - 事前正規化（H1削除 / 引用H2 / アクセス日削除）
    cmds:
      - FILES=$({{.TARGETS_CMD}}); node scripts/run_codex.mjs doc/playbooks/20_normalize_refs_and_headings.md $FILES

  codex:escape-symbols:
    desc: Step 2b - 記号エスケープ（< → &lt;、& → &amp;、$ → \$）
    cmds:
      - FILES=$({{.TARGETS_CMD}}); node scripts/run_codex.mjs doc/playbooks/21_escape_symbols.md $FILES

  fallback:normalize-refs:
    cmds:
      - FILES=$({{.TARGETS_CMD}}); node scripts/normalize_refs_deterministic.mjs $FILES

  codex:table-shorten:
    desc: Step 3 - テーブル短縮（1列目リンク化＋出典URL列削除）
    cmds:
      - FILES=$({{.TARGETS_CMD}}); node scripts/run_codex.mjs doc/playbooks/30_table_shorten.md $FILES

  codex:link-citations:
    desc: Step 4 - 引用番号 ↔ 文献の相互リンク化（Codex）
    cmds:
      - FILES=$({{.TARGETS_CMD}}); node scripts/run_codex.mjs doc/playbooks/40_link_citations.md $FILES

  codex:dedupe-citations:
    desc: Step 5 - 過剰な引用番号を除去し、セクション末にまとめる（Codex）
    cmds:
      - FILES=$({{.TARGETS_CMD}}); node scripts/run_codex.mjs doc/playbooks/50_dedupe_citations.md $FILES

  codex:internal-links:
    desc: Step 6 - 既存レビューへの内部リンク付与（最初の1回のみ）
    cmds:
      - FILES=$({{.TARGETS_CMD}}); node scripts/run_codex.mjs doc/playbooks/60_internal_links.md $FILES

  codex:insert-measurements-mcp:
    desc: Step 7 (MCP) - 測定グラフを自動取得してMDXへ挿入（Playwright+Filesystem）
    cmds:
      - FILES=$({{.TARGETS_CMD}}); node scripts/run_codex.mjs doc/playbooks/70_insert_measurements_mcp.md $FILES

  gemini:insert-measurements-old:
    desc: Step 7 (Gemini) - 測定グラフ挿入（非対話）
    cmds:
      - |
        FILES=$({{.TARGETS_CMD}})
        printf "/measurements:insert %s\n" "$FILES" | gemini \
          --include-directories . \
          --approval-mode auto_edit \
          --allowed-tools write_file,read_file,replace,glob,search_file_content,browser_navigate,browser_evaluate,browser_query_selector,browser_query_selector_all,browser_screenshot,request_get \

  gemini:insert-measurements:
    desc: Step 7 (Gemini) - 測定グラフ挿入（非対話）
    cmds:
      - |
        FILES=$({{.TARGETS_CMD}})
        PROMPT=$'# 実行指示\n@doc/playbooks/70_insert_measurements_mcp_gemini.md\n\n# 対象MDX'
        for f in $FILES; do PROMPT="$PROMPT"$'\n'"@$f"; done
        gemini \
          --approval-mode auto_edit \
          --allowed-tools write_file,read_file,replace,glob,search_file_content,browser_navigate,browser_evaluate,browser_query_selector,browser_query_selector_all,browser_screenshot,request_get \
          -p "$PROMPT"

  codex:hero:
    desc: 【非推奨】Step 9 (Codex+MCP) - 公式サイトからヒーロー画像DL→frontmatter.heroImage更新（拡張子自動）
    cmds:
      - FILES=$({{.TARGETS_CMD}}); node scripts/run_codex.mjs doc/playbooks/79_fetch_and_set_hero_mcp.md $FILES

  claude:hero:
    desc: Step 9 (Claude+MCP) - 公式サイトからヒーロー画像DL→frontmatter.heroImage更新（拡張子自動）
    cmds:
      - FILES=$({{.TARGETS_CMD}}); node scripts/run_claude.mjs doc/playbooks/79_fetch_and_set_hero_mcp.md $FILES

  build:catalog:
    desc: 全記事のメタカタログを構築
    cmds:
      - node scripts/build_catalog.mjs

  codex:related:auto:
    desc: Step 8 - frontmatter.relatedArticles を自動設定/補完
    cmds:
      - FILES=$({{.TARGETS_CMD}}); node scripts/run_codex.mjs doc/playbooks/80_related_auto.md $FILES

  codex:tags:auto:
    desc: Step 13 - catalog.json の人気度に基づき frontmatter.tags を人気順で上書き（最大7件）
    cmds:
      - FILES=$({{.TARGETS_CMD}}); node scripts/run_codex.mjs doc/playbooks/83_tags_from_catalog.md $FILES

  claude:translate-en:
    desc: 英語版記事を生成/更新（Claude：高品質翻訳、MD/MDX対応、frontmatter整備）
    cmds:
      - FILES=$({{.TARGETS_CMD}}); node scripts/run_claude.mjs doc/playbooks/90_translate_en.md $FILES

  filemove:
    desc: reviews/_incoming → reviews/ にファイル移動（冪等・git mv対応）
    cmds:
      - |
        set -euo pipefail
        FILES="${FILES:-$({{.TARGETS_CMD}})}"
        if [ -z "${FILES}" ]; then
          echo "No target files. Set FILES or adjust TARGETS_CMD."; exit 0
        fi

        # 既定は上書き禁止。FORCE=1 で上書き許可。
        MV_FLAGS="-n"
        [ "${FORCE:-0}" = "1" ] && MV_FLAGS="-f"

        for f in ${FILES}; do
          # 対象は .md / .mdx のみ
          case "$f" in
            *.md|*.mdx) ;;
            *) echo "skip (not md/mdx): $f"; continue ;;
          esac

          # _incoming から reviews 直下へ（サブフォルダは温存）
          dest="${f/src\/content\/reviews\/_incoming\//src/content/reviews/}"
          if [ "$dest" = "$f" ]; then
            echo "skip (not in _incoming): $f"; continue
          fi

          mkdir -p "$(dirname "$dest")"

          # DRY=1 でドライラン（実際には移動しない）
          if [ "${DRY:-0}" = "1" ]; then
            echo "[DRY] mv ${MV_FLAGS} -- '$f' '$dest'"
            continue
          fi

          mv ${MV_FLAGS} -- "$f" "$dest"

          echo "moved: $f -> $dest"
        done


  build:
    desc: Astro のビルド
    cmds:
      - pnpm build
