name: After CF Pages deploy, ping WebSub
on:
  push:
    branches: [ main ]

jobs:
  after-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Cloudflare Pages production deployment
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}   # Pages Read権限
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_PAGES_PROJECT: audio-review
          GIT_SHA: ${{ github.sha }}
        run: |
          sudo apt-get update && sudo apt-get install -y jq
          for i in {1..120}; do
            RESP=$(curl -s -H "Authorization: Bearer $CF_API_TOKEN" \
              "https://api.cloudflare.com/client/v4/accounts/$CF_ACCOUNT_ID/pages/projects/$CF_PAGES_PROJECT/deployments?env=production&per_page=1")
            STATUS=$(echo "$RESP" | jq -r '.result[0].latest_stage.status')
            DEP_SHA=$(echo "$RESP" | jq -r '.result[0].deployment_trigger.metadata.commit_hash')
            echo "status=$STATUS commit=$DEP_SHA"
            if [ "$STATUS" = "success" ] && [ "$DEP_SHA" = "$GIT_SHA" ]; then
              break
            fi
            sleep 10
          done
          [ "$STATUS" = "success" ] || { echo "Deployment not successful"; exit 1; }
          [ "$DEP_SHA" = "$GIT_SHA" ] || { echo "Latest production is not this commit"; exit 1; }

      - name: Call Pages Function (publish WebSub)
        run: |
          curl -fsS -X POST https://audiomatome.com/ping-hubs
